config/routes.rb
Rails.application.routes.draw do
  resources :pigs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pig.rb
class Pig < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pigs_controller.rb
class PigsController < ApplicationController
  before_action :set_pig, only: %i[ show edit update destroy ]

  # GET /pigs or /pigs.json
  def index
    @pigs = Pig.all
  end

  # GET /pigs/1 or /pigs/1.json
  def show
  end

  # GET /pigs/new
  def new
    @pig = Pig.new
  end

  # GET /pigs/1/edit
  def edit
  end

  # POST /pigs or /pigs.json
  def create
    @pig = Pig.new(pig_params)

    respond_to do |format|
      if @pig.save
        format.html { redirect_to @pig, notice: "Pig was successfully created." }
        format.json { render :show, status: :created, location: @pig }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pigs/1 or /pigs/1.json
  def update
    respond_to do |format|
      if @pig.update(pig_params)
        format.html { redirect_to @pig, notice: "Pig was successfully updated." }
        format.json { render :show, status: :ok, location: @pig }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pigs/1 or /pigs/1.json
  def destroy
    @pig.destroy!

    respond_to do |format|
      format.html { redirect_to pigs_path, status: :see_other, notice: "Pig was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pig
      @pig = Pig.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def pig_params
      params.expect(pig: [ :name, :dead ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pigs_helper.rb
module PigsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Proj" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pigs/_form.html.erb
<%= form_with(model: pig) do |form| %>
  <% if pig.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pig.errors.count, "error") %> prohibited this pig from being saved:</h2>

      <ul>
        <% pig.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :dead, style: "display: block" %>
    <%= form.checkbox :dead %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pigs/_pig.html.erb
<div id="<%= dom_id pig %>">
  <p>
    <strong>Name:</strong>
    <%= pig.name %>
  </p>

  <p>
    <strong>Dead:</strong>
    <%= pig.dead %>
  </p>

</div>

app/views/pigs/edit.html.erb
<% content_for :title, "Editing pig" %>

<h1>Editing pig</h1>

<%= render "form", pig: @pig %>

<br>

<div>
  <%= link_to "Show this pig", @pig %> |
  <%= link_to "Back to pigs", pigs_path %>
</div>

app/views/pigs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pigs" %>

<h1>Pigs</h1>

<div id="pigs">
  <% @pigs.each do |pig| %>
    <%= render pig %>
    <p>
      <%= link_to "Show this pig", pig %>
    </p>
  <% end %>
</div>

<%= link_to "New pig", new_pig_path %>

app/views/pigs/new.html.erb
<% content_for :title, "New pig" %>

<h1>New pig</h1>

<%= render "form", pig: @pig %>

<br>

<div>
  <%= link_to "Back to pigs", pigs_path %>
</div>

app/views/pigs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pig %>

<div>
  <%= link_to "Edit this pig", edit_pig_path(@pig) %> |
  <%= link_to "Back to pigs", pigs_path %>

  <%= button_to "Destroy this pig", @pig, method: :delete %>
</div>